name: Terraform Module Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-modue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/github
    env:
      TF_CLOUD_HOSTNAME: ${{vars.TF_CLOUD_HOSTNAME}}
      TF_CLOUD_ORGANIZATION: ${{vars.TF_CLOUD_ORGANIZATION}}
      TF_WORKSPACE: ${{vars.TF_WORKSPACE}}
      TF_TOKEN_app_terraform_io: ${{secrets.TF_TOKEN}}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

        # The following is only required for testing new changes in the branch
        # CLI workflow cannot upload the module files that are in upper directory
      - name: Set up local module
        run: |
          mkdir -p modules/pet
          cp ../../*.tf modules/pet
          cp -R ../../templates modules/pet/
          cat << EOF > backend.tf
          terraform {
          cloud {}
          }
          EOF

          ls -lh
      
      - name: Terraform Version
        id: version
        run: terraform -v

      - name: Initialize Terraform
        id: init
        run: terraform init
      
      - name: Validate Terraform
        id: validate
        run: terraform validate

      - name: Plan changes
        id: plan
        run: terraform plan
      
      - name: Apply changes
        id: apply
        run: terraform apply -auto-approve
      
      - name: Run additional tests
        id: tests
        run: |
          terraform state list
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
          APPLY: ${{ steps.apply.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan and Apply</summary>

            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`

            \`\`\`terraform\n
            ${process.env.Apply}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })


      - name: Destroy
        run: terraform destroy -auto-approve